---
- name: Install Debian OS packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - git
    - openjdk-7-jdk
  when: marathon_build_source == "yes"

# == Templates ==
- name: Create Marathon init file
  template: src=marathon.j2 dest=/etc/init/marathon.conf
    owner="root" group="root" mode=0664