---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add Mesosphere repo
  apt_repository: repo="{{marathon_apt_repo}}" state=present

- name: Install Marathon package
  apt: pkg=marathon={{marathon_version}}-1.0 state=present update_cache=yes

- name: Create Marathon conf directory
  file: path=/etc/marathon/conf state=directory

- name: Set master option
  template: src=master.j2 dest=/etc/marathon/conf/master

# == Templates ==
# - name: Create / overwrite Marathon init file
#   template: src=marathon.j2 dest=/etc/init/marathon.conf
#     owner="root" group="root" mode=0664