---

# == base ==
version: "0.1.0"

# == source ==
source_dir: "/tmp/marathon"
source_repo: "https://github.com/mesosphere/marathon.git"
marathon_version: "marathon-0.3.0"
# version: is skipped as we always go directly to source
cleanup: true

# == install ==
install_location: "/opt/marathon"
install_jar: "{{install_location}}/marathon.jar"
target_jar_name: "{{marathon_version}}-jar-with-dependencies.jar"
target_jar_location: "{{source_dir}}/target/{{target_jar_name}}"

# == marathon conf ==
runtime_memory_options: "-Xmx512m"
runtime_lib_path: "/usr/local/lib"
runtime_marathon_jar: "/opt/marathon/marathon.jar"
runtime_zookeeper_hosts: "localhost:2181"
runtime_master: "zk://localhost:2181/mesos"
